DROP TABLE POSITION CASCADE CONSTRAINTS;

CREATE TABLE POSITION
(
  P_POSITION_ID          NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 21 MAXVALUE 999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP) NOT NULL,
  P_POSITION_DESC        VARCHAR2(100 BYTE)     NOT NULL,
  P_POSITION_DEPARTMENT  VARCHAR2(150 BYTE)     NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX POSITION_PK ON POSITION
(P_POSITION_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE POSITION ADD (
  CONSTRAINT POSITION_PK
  PRIMARY KEY
  (P_POSITION_ID)
  USING INDEX POSITION_PK
  ENABLE VALIDATE);


SET DEFINE OFF;
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (1, 'YAZILIM UZMANI', 'IT');
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (2, 'AG UZMAN YARDIMCISI', 'IT');
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (4, 'AG UZMANI', 'IT');
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (5, 'UZAKTAN DESTEK UZMANI', 'IT');
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (6, 'BILGI SISTEMLERI MÜDÜRÜ', 'IT');
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (7, 'YAZILIM UZMAN YARDIMCISI', 'IT');
Insert into POSITION
   (P_POSITION_ID, P_POSITION_DESC, P_POSITION_DEPARTMENT)
 Values
   (8, 'GENEL MÜDÜR', 'GMD');
COMMIT;
